"""Auto-generated by tools/generate_game_badge_registry.py. Do not edit."""

MINIGAME_DAILY_CHANCE = 46

CHAPTER_7_PAGE_IDS = [12007, 12008, 12009, 12010, 12011, 12029, 12047, 12054]

PLAY_COUNT_TRACKS = {
    1: {
        "tiers": [
            {"badge_id": 10576, "threshold": 5},
            {"badge_id": 10577, "threshold": 25},
            {"badge_id": 10578, "threshold": 100},
        ],
    },
    2: {
        "tiers": [
            {"badge_id": 10580, "threshold": 5},
            {"badge_id": 10581, "threshold": 25},
            {"badge_id": 10582, "threshold": 100},
        ],
    },
    7: {
        "tiers": [
            {"badge_id": 10584, "threshold": 5},
            {"badge_id": 10585, "threshold": 25},
            {"badge_id": 10586, "threshold": 100},
        ],
    },
    8: {
        "tiers": [
            {"badge_id": 10592, "threshold": 5},
            {"badge_id": 10593, "threshold": 25},
            {"badge_id": 10594, "threshold": 100},
        ],
    },
    9: {
        "tiers": [
            {"badge_id": 10588, "threshold": 5},
            {"badge_id": 10589, "threshold": 25},
            {"badge_id": 10590, "threshold": 100},
        ],
    },
    10: {
        "tiers": [
            {"badge_id": 10600, "threshold": 5},
            {"badge_id": 10601, "threshold": 25},
            {"badge_id": 10602, "threshold": 100},
        ],
    },
    11: {
        "tiers": [
            {"badge_id": 10682, "threshold": 5},
            {"badge_id": 10683, "threshold": 25},
            {"badge_id": 10684, "threshold": 100},
        ],
    },
    14: {
        "tiers": [
            {"badge_id": 10740, "threshold": 5},
            {"badge_id": 10741, "threshold": 25},
            {"badge_id": 10742, "threshold": 100},
        ],
    },
    15: {
        "tiers": [
            {"badge_id": 10761, "threshold": 5},
            {"badge_id": 10762, "threshold": 25},
            {"badge_id": 10763, "threshold": 100},
        ],
    },
    43: {
        "tiers": [
            {"badge_id": 10785, "threshold": 5},
            {"badge_id": 10786, "threshold": 25},
            {"badge_id": 10787, "threshold": 100},
        ],
    },
    44: {
        "tiers": [
            {"badge_id": 10817, "threshold": 5},
            {"badge_id": 10818, "threshold": 25},
            {"badge_id": 10819, "threshold": 100},
        ],
    },
    45: {
        "tiers": [
            {"badge_id": 10889, "threshold": 5},
            {"badge_id": 10890, "threshold": 25},
            {"badge_id": 10891, "threshold": 100},
        ],
    },
    47: {
        "tiers": [
            {"badge_id": 10970, "threshold": 5},
            {"badge_id": 10971, "threshold": 25},
            {"badge_id": 10972, "threshold": 100},
        ],
    },
    48: {
        "tiers": [
            {"badge_id": 11015, "threshold": 5},
            {"badge_id": 11016, "threshold": 25},
            {"badge_id": 11017, "threshold": 100},
        ],
    },
    49: {
        "tiers": [
            {"badge_id": 10981, "threshold": 5},
            {"badge_id": 10982, "threshold": 25},
            {"badge_id": 10983, "threshold": 100},
        ],
    },
}

HIGH_SCORE_BADGES = {
    1: {"badge_id": 10579, "threshold": 40000},
    2: {"badge_id": 10583, "threshold": 15000},
    7: {"badge_id": 10587, "threshold": 110000},
    8: {"badge_id": 10595, "threshold": 55000},
    9: {"badge_id": 10591, "threshold": 40000},
    10: {"badge_id": 10603, "threshold": 50000},
    11: {"badge_id": 10685, "threshold": 50000},
    14: {"badge_id": 10743, "threshold": 70000},
    15: {"badge_id": 10764, "threshold": 20000},
    43: {"badge_id": 10788, "threshold": 130000},
    44: {"badge_id": 10820, "threshold": 85000},
    45: {"badge_id": 10892, "threshold": 50000},
    47: {"badge_id": 10973, "threshold": 100000},
    48: {"badge_id": 11018, "threshold": 105000},
    49: {"badge_id": 10984, "threshold": 155000},
}

DAILY_SPIN_PLAY_TRACK = {
    "tiers": [
        {"badge_id": 10899, "threshold": 5},
        {"badge_id": 10900, "threshold": 25},
        {"badge_id": 10901, "threshold": 100},
    ],
}

DAILY_SPIN_ROCK_WIN_TRACK = {
    "tiers": [
        {"badge_id": 10974, "threshold": 5},
        {"badge_id": 10975, "threshold": 20},
        {"badge_id": 10976, "threshold": 50},
    ],
}

DAILY_SPIN_PRIZE_BADGE_IDS = frozenset([10903, 10902, 11130])

PLAY_COUNT_GAME_IDS = frozenset(PLAY_COUNT_TRACKS.keys())
HIGH_SCORE_GAME_IDS = frozenset(HIGH_SCORE_BADGES.keys())

ALL_GAME_BADGE_IDS = frozenset([10576, 10577, 10578, 10579, 10580, 10581, 10582, 10583, 10584, 10585, 10586, 10587, 10588, 10589, 10590, 10591, 10592, 10593, 10594, 10595, 10600, 10601, 10602, 10603, 10682, 10683, 10684, 10685, 10740, 10741, 10742, 10743, 10761, 10762, 10763, 10764, 10785, 10786, 10787, 10788, 10817, 10818, 10819, 10820, 10889, 10890, 10891, 10892, 10899, 10900, 10901, 10902, 10903, 10970, 10971, 10972, 10973, 10974, 10975, 10976, 10981, 10982, 10983, 10984, 11015, 11016, 11017, 11018, 11130])

BADGE_ID_TO_GAME_ID = {
    10576: 1,
    10577: 1,
    10578: 1,
    10580: 2,
    10581: 2,
    10582: 2,
    10584: 7,
    10585: 7,
    10586: 7,
    10592: 8,
    10593: 8,
    10594: 8,
    10588: 9,
    10589: 9,
    10590: 9,
    10600: 10,
    10601: 10,
    10602: 10,
    10682: 11,
    10683: 11,
    10684: 11,
    10740: 14,
    10741: 14,
    10742: 14,
    10761: 15,
    10762: 15,
    10763: 15,
    10785: 43,
    10786: 43,
    10787: 43,
    10817: 44,
    10818: 44,
    10819: 44,
    10889: 45,
    10890: 45,
    10891: 45,
    10970: 47,
    10971: 47,
    10972: 47,
    11015: 48,
    11016: 48,
    11017: 48,
    10981: 49,
    10982: 49,
    10983: 49,
    10579: 1,
    10583: 2,
    10587: 7,
    10595: 8,
    10591: 9,
    10603: 10,
    10685: 11,
    10743: 14,
    10764: 15,
    10788: 43,
    10820: 44,
    10892: 45,
    10973: 47,
    11018: 48,
    10984: 49,
}
