"""Auto-generated by tools/generate_ingredient_badge_registry.py. Do not edit."""

CHAPTER_10_PAGE_IDS = [12019, 12020, 12021, 12022, 12023, 12024, 12025, 12026, 12027, 12028, 12032, 12033]

PRETIER_TOTAL = 1000

ROYAL_SEGMENT_GOAL = 9000

ROYAL_CUMULATIVE_THRESHOLD = 10000

COLLECTION_BADGES = {
    8001: {
        "page_id": 12021,
        "subject": 'oak leaves',
        "tiers": [
            {"badge_id": 10646, "threshold": 50},
            {"badge_id": 10647, "threshold": 200},
            {"badge_id": 10648, "threshold": 1000},
            {"badge_id": 10649, "threshold": 10000},
        ],
    },
    8002: {
        "page_id": 12021,
        "subject": 'maple leaves',
        "tiers": [
            {"badge_id": 10642, "threshold": 50},
            {"badge_id": 10643, "threshold": 200},
            {"badge_id": 10644, "threshold": 1000},
            {"badge_id": 10645, "threshold": 10000},
        ],
    },
    8003: {
        "page_id": 12022,
        "subject": 'ivy',
        "tiers": [
            {"badge_id": 10678, "threshold": 50},
            {"badge_id": 10679, "threshold": 200},
            {"badge_id": 10680, "threshold": 1000},
            {"badge_id": 10681, "threshold": 10000},
        ],
    },
    8004: {
        "page_id": 12020,
        "subject": 'rose petals',
        "tiers": [
            {"badge_id": 10630, "threshold": 50},
            {"badge_id": 10631, "threshold": 200},
            {"badge_id": 10632, "threshold": 1000},
            {"badge_id": 10633, "threshold": 10000},
        ],
    },
    8005: {
        "page_id": 12019,
        "subject": 'daisy petals',
        "tiers": [
            {"badge_id": 10622, "threshold": 50},
            {"badge_id": 10623, "threshold": 200},
            {"badge_id": 10624, "threshold": 1000},
            {"badge_id": 10625, "threshold": 10000},
        ],
    },
    8006: {
        "page_id": 12020,
        "subject": 'lily petals',
        "tiers": [
            {"badge_id": 10626, "threshold": 50},
            {"badge_id": 10627, "threshold": 200},
            {"badge_id": 10628, "threshold": 1000},
            {"badge_id": 10629, "threshold": 10000},
        ],
    },
    8007: {
        "page_id": 12019,
        "subject": 'buttercup petals',
        "tiers": [
            {"badge_id": 10618, "threshold": 50},
            {"badge_id": 10619, "threshold": 200},
            {"badge_id": 10620, "threshold": 1000},
            {"badge_id": 10621, "threshold": 10000},
        ],
    },
    8008: {
        "page_id": 12025,
        "subject": 'spider silk',
        "tiers": [
            {"badge_id": 10666, "threshold": 50},
            {"badge_id": 10667, "threshold": 200},
            {"badge_id": 10668, "threshold": 1000},
            {"badge_id": 10669, "threshold": 10000},
        ],
    },
    8009: {
        "page_id": 12026,
        "subject": 'meadow grass',
        "tiers": [
            {"badge_id": 10670, "threshold": 50},
            {"badge_id": 10671, "threshold": 200},
            {"badge_id": 10672, "threshold": 1000},
            {"badge_id": 10673, "threshold": 10000},
        ],
    },
    8010: {
        "page_id": 12024,
        "subject": 'sunflower seeds',
        "tiers": [
            {"badge_id": 10658, "threshold": 50},
            {"badge_id": 10659, "threshold": 200},
            {"badge_id": 10660, "threshold": 1000},
            {"badge_id": 10661, "threshold": 10000},
        ],
    },
    8011: {
        "page_id": 12024,
        "subject": 'acorns',
        "tiers": [
            {"badge_id": 10654, "threshold": 50},
            {"badge_id": 10655, "threshold": 200},
            {"badge_id": 10656, "threshold": 1000},
            {"badge_id": 10657, "threshold": 10000},
        ],
    },
    8012: {
        "page_id": 12023,
        "subject": 'blueberries',
        "tiers": [
            {"badge_id": 10634, "threshold": 50},
            {"badge_id": 10635, "threshold": 200},
            {"badge_id": 10636, "threshold": 1000},
            {"badge_id": 10637, "threshold": 10000},
        ],
    },
    8013: {
        "page_id": 12026,
        "subject": 'dandelion fluff',
        "tiers": [
            {"badge_id": 10674, "threshold": 50},
            {"badge_id": 10675, "threshold": 200},
            {"badge_id": 10676, "threshold": 1000},
            {"badge_id": 10677, "threshold": 10000},
        ],
    },
    8014: {
        "page_id": 12023,
        "subject": 'rasberries',
        "tiers": [
            {"badge_id": 10638, "threshold": 50},
            {"badge_id": 10639, "threshold": 200},
            {"badge_id": 10640, "threshold": 1000},
            {"badge_id": 10641, "threshold": 10000},
        ],
    },
    8015: {
        "page_id": 12022,
        "subject": 'pine needles',
        "tiers": [
            {"badge_id": 10650, "threshold": 50},
            {"badge_id": 10651, "threshold": 200},
            {"badge_id": 10652, "threshold": 1000},
            {"badge_id": 10653, "threshold": 10000},
        ],
    },
    8016: {
        "page_id": 12025,
        "subject": 'snow flakes',
        "tiers": [
            {"badge_id": 10662, "threshold": 50},
            {"badge_id": 10663, "threshold": 200},
            {"badge_id": 10664, "threshold": 1000},
            {"badge_id": 10665, "threshold": 10000},
        ],
    },
    8017: {
        "page_id": 12028,
        "subject": 'honeycombs',
        "tiers": [
            {"badge_id": 10690, "threshold": 50},
            {"badge_id": 10691, "threshold": 200},
            {"badge_id": 10692, "threshold": 1000},
            {"badge_id": 10693, "threshold": 10000},
        ],
    },
    8018: {
        "page_id": 12027,
        "subject": 'twigs',
        "tiers": [
            {"badge_id": 10686, "threshold": 50},
            {"badge_id": 10687, "threshold": 200},
            {"badge_id": 10688, "threshold": 1000},
            {"badge_id": 10689, "threshold": 10000},
        ],
    },
    8019: {
        "page_id": 12032,
        "subject": 'truffles',
        "tiers": [
            {"badge_id": 10748, "threshold": 50},
            {"badge_id": 10712, "threshold": 200},
            {"badge_id": 10713, "threshold": 1000},
            {"badge_id": 10714, "threshold": 10000},
        ],
    },
    8020: {
        "page_id": 12033,
        "subject": 'blue gems',
        "tiers": [
            {"badge_id": 10719, "threshold": 50},
            {"badge_id": 10720, "threshold": 200},
            {"badge_id": 10721, "threshold": 1000},
            {"badge_id": 10722, "threshold": 10000},
        ],
    },
    8021: {
        "page_id": 12033,
        "subject": 'yellow gems',
        "tiers": [
            {"badge_id": 10715, "threshold": 50},
            {"badge_id": 10716, "threshold": 200},
            {"badge_id": 10717, "threshold": 1000},
            {"badge_id": 10718, "threshold": 10000},
        ],
    },
    8022: {
        "page_id": 12028,
        "subject": 'feathers',
        "tiers": [
            {"badge_id": 10744, "threshold": 50},
            {"badge_id": 10745, "threshold": 200},
            {"badge_id": 10746, "threshold": 1000},
            {"badge_id": 10747, "threshold": 10000},
        ],
    },
    8023: {
        "page_id": 12032,
        "subject": 'metal',
        "tiers": [
            {"badge_id": 10723, "threshold": 50},
            {"badge_id": 10724, "threshold": 200},
            {"badge_id": 10725, "threshold": 1000},
            {"badge_id": 10726, "threshold": 10000},
        ],
    },
}

ITEM_IDS = frozenset(COLLECTION_BADGES.keys())

ALL_COLLECTION_BADGE_IDS = frozenset(
    tier['badge_id']
    for entry in COLLECTION_BADGES.values()
    for tier in entry['tiers']
)

BADGE_ID_TO_ITEM_ID = {
    10646: 8001,
    10647: 8001,
    10648: 8001,
    10649: 8001,
    10642: 8002,
    10643: 8002,
    10644: 8002,
    10645: 8002,
    10678: 8003,
    10679: 8003,
    10680: 8003,
    10681: 8003,
    10630: 8004,
    10631: 8004,
    10632: 8004,
    10633: 8004,
    10622: 8005,
    10623: 8005,
    10624: 8005,
    10625: 8005,
    10626: 8006,
    10627: 8006,
    10628: 8006,
    10629: 8006,
    10618: 8007,
    10619: 8007,
    10620: 8007,
    10621: 8007,
    10666: 8008,
    10667: 8008,
    10668: 8008,
    10669: 8008,
    10670: 8009,
    10671: 8009,
    10672: 8009,
    10673: 8009,
    10658: 8010,
    10659: 8010,
    10660: 8010,
    10661: 8010,
    10654: 8011,
    10655: 8011,
    10656: 8011,
    10657: 8011,
    10634: 8012,
    10635: 8012,
    10636: 8012,
    10637: 8012,
    10674: 8013,
    10675: 8013,
    10676: 8013,
    10677: 8013,
    10638: 8014,
    10639: 8014,
    10640: 8014,
    10641: 8014,
    10650: 8015,
    10651: 8015,
    10652: 8015,
    10653: 8015,
    10662: 8016,
    10663: 8016,
    10664: 8016,
    10665: 8016,
    10690: 8017,
    10691: 8017,
    10692: 8017,
    10693: 8017,
    10686: 8018,
    10687: 8018,
    10688: 8018,
    10689: 8018,
    10748: 8019,
    10712: 8019,
    10713: 8019,
    10714: 8019,
    10719: 8020,
    10720: 8020,
    10721: 8020,
    10722: 8020,
    10715: 8021,
    10716: 8021,
    10717: 8021,
    10718: 8021,
    10744: 8022,
    10745: 8022,
    10746: 8022,
    10747: 8022,
    10723: 8023,
    10724: 8023,
    10725: 8023,
    10726: 8023,
}
