"""Leaderboard-related badge IDs and badge-book pages."""

GREAT_GAMES_HONORS_BADGE_ID = 10869
GREAT_GAMES_HONORS_PAGE_ID = 12042

LEADERBOARD_BADGE_PAGE_BY_ID = {
    GREAT_GAMES_HONORS_BADGE_ID: GREAT_GAMES_HONORS_PAGE_ID,
}
