# SPRING
CHERRYBLOSSOM_HEIGHTS = 100
SPRINGTIME_ORCHARD = 101
DEWDROP_VALE = 102
NEVERBERRY_THICKET = 103
TREETOP_BEND = 104
TROOP_BUTTERFLY_HIDEOUT = 105
TROOP_OTTER_HIDEOUT = 106

# AUTUMN
ACORN_SUMMIT = 200
COTTONPUFF_FIELD = 201
MAPLE_TREE_HILL = 202
PUMPKIN_PATCH = 203
TROOP_RABBIT_HIDEOUT = 204
TROOP_TURTLE_HIDEOUT = 205

# WINTER
EVERGREEN_OVERLOOK = 300
SNOWCAP_GLADE = 301
CHILLY_FALLS = 302
ICE_PALACE = 303
FROSTED_FOREST = 304

# SUMMER
PALM_TREE_COVE = 400
SUNFLOWER_GULLY = 401
NEVERFRUIT_GROVE = 402
MERMAID_GROTTO = 403
TROOP_GLOWWORM_HIDEOUT = 404

# HAVENDISH SQUARE
HAVENDISH_SQUARE = 500
FAIRY_TALE_THEATER = 501
THE_BALLROOM = 502
THE_TEAROOM = 503
LIZZYS_HOUSE = 504
FAIRY_COLISEUM = 505
PIXIE_POSTINGS = 1200
PIXIE_POSTINGS_CONSTRUCTION = 1201

MEADOW_ZONES_LIST: list[int] = [
    CHERRYBLOSSOM_HEIGHTS,
    SPRINGTIME_ORCHARD,
    DEWDROP_VALE,
    NEVERBERRY_THICKET,
    TREETOP_BEND,
    TROOP_BUTTERFLY_HIDEOUT,
    TROOP_OTTER_HIDEOUT,
    ACORN_SUMMIT,
    COTTONPUFF_FIELD,
    MAPLE_TREE_HILL,
    PUMPKIN_PATCH,
    TROOP_RABBIT_HIDEOUT,
    TROOP_TURTLE_HIDEOUT,
    EVERGREEN_OVERLOOK,
    SNOWCAP_GLADE,
    CHILLY_FALLS,
    ICE_PALACE,
    FROSTED_FOREST,
    PALM_TREE_COVE,
    SUNFLOWER_GULLY,
    NEVERFRUIT_GROVE,
    MERMAID_GROTTO,
    TROOP_GLOWWORM_HIDEOUT,
    HAVENDISH_SQUARE,
    FAIRY_TALE_THEATER,
    THE_BALLROOM,
    THE_TEAROOM,
    LIZZYS_HOUSE,
    FAIRY_COLISEUM
]

# QUEST ZONES
FAWNS_HIDEOUT = 800
IRIDESSAS_GLADE = 801
ROSETTAS_GARDEN = 802
SILVERMISTS_GROTTO = 803
TINKERS_NOOK = 804
KITS_PLACE = 805
ELIXAS_HOSPITAL = 806
PIXIE_DUST_MILL = 807
MARINAS_PLACE = 808

# GAMES
FIREFLY_LIGHT_UP_GAME = 50001
BUBBLE_BOUNCE_GAME = 50002
WATER_WEB_GAME = 50007
HARVEST_HUSTLE_GAME = 50008
PETAL_PICKUP_GAME = 50009
FAIRY_FIREWORKS_GAME = 50010
SNOWFLAKE_SWEEP_GAME = 50011
TINKER_TOSS_GAME = 50014
SNOWY_LULLABY_GAME = 50015
SEED_SORTING_GAME = 50043
FIRST_FLIGHT_GAME = 50044
BUTTERFLY_PAINTER_GAME = 50045
VIDIAS_DAILY_SPIN = 50046
PINECONE_POP_GAME = 50047
LIGHT_PIPE_GAME = 50048
GEM_JUGGLE_GAME = 50049

GAMES_ZONE_LIST: list[int] = [
    FIREFLY_LIGHT_UP_GAME,
    BUBBLE_BOUNCE_GAME,
    WATER_WEB_GAME,
    HARVEST_HUSTLE_GAME,
    PETAL_PICKUP_GAME,
    FAIRY_FIREWORKS_GAME,
    SNOWFLAKE_SWEEP_GAME,
    TINKER_TOSS_GAME,
    SNOWY_LULLABY_GAME,
    SEED_SORTING_GAME,
    FIRST_FLIGHT_GAME,
    BUTTERFLY_PAINTER_GAME,
    VIDIAS_DAILY_SPIN,
    PINECONE_POP_GAME,
    LIGHT_PIPE_GAME,
    GEM_JUGGLE_GAME
]

# SHOPS
BELLAS_BAUBLES = 110000
GARDEN_SUPPLY = 110001
SUMMIT_STYLE = 110002
GALES_OUTFITTERS = 110003
CASSIES_COSTUME_SHOP = 110004
COALS_CLOTHIERS = 110005
GAVINS_GEAR = 110006
ZEPHYRS_ZOOM_ROOM = 110007
PIXIE_POST_OFFICE = 110008
QUEENS_BOUTIQUE = 110009
HARMONYS_SWEET_SHOP = 110010
SPIKES_SWEETS = 110011
EMBERS_ESSENTIALS = 111002
PHOEBES_PARTY_FAVORS = 113000
SCHELLYS_HAIR_SALON = 114000
BECKS_ANIMAL_NURSERY = 115000
NEVILLES_NEW_HOMES = 116000
PRISMS_PIXIE_SPA = 117000

SHOPS_ZONE_LIST: list[int] = [
    BELLAS_BAUBLES,
    GARDEN_SUPPLY,
    SUMMIT_STYLE,
    GALES_OUTFITTERS,
    CASSIES_COSTUME_SHOP,
    COALS_CLOTHIERS,
    GAVINS_GEAR,
    ZEPHYRS_ZOOM_ROOM,
    PIXIE_POST_OFFICE,
    QUEENS_BOUTIQUE,
    HARMONYS_SWEET_SHOP,
    SPIKES_SWEETS,
    PHOEBES_PARTY_FAVORS,
    SCHELLYS_HAIR_SALON,
    BECKS_ANIMAL_NURSERY,
    NEVILLES_NEW_HOMES,
    PRISMS_PIXIE_SPA
]
