from game.fairies.ai import ZoneConstants

# Minigame IDs (from constants)
MINIGAME_FIREFLY_LIGHT_UP = 1
MINIGAME_BUBBLE_BOUNCE = 2
MINIGAME_CATERPILLAR_CUTTER = 3
MINIGAME_PATTERN_PLACING = 4
MINIGAME_SPIDER_STITCHING = 5
MINIGAME_ROLLYPOLLY_DYING = 6
MINIGAME_WATER_WEB = 7
MINIGAME_HARVEST_HUSTLE = 8
MINIGAME_PETAL_PICKUP = 9
MINIGAME_FAIRY_FIREWORKS = 10
MINIGAME_SNOWFLAKE_SWEEP = 11
MINIGAME_PASS_POPCORN = 12
MINIGAME_SIMONE_SAYS = 13
MINIGAME_TINKER_TOSS = 14
MINIGAME_LULLABY = 15
MINIGAME_ROCK_PAPER_SCISSOR = 16
MINIGAME_POURING = 38
MINIGAME_BAKING = 39
MINIGAME_MIXING = 40
MINIGAME_TINKERING = 41
MINIGAME_SORTING_SUPPLIES_TUTORIAL = 42
MINIGAME_SEED_SORTING = 43
MINIGAME_FIRST_FLIGHT = 44
MINIGAME_BUTTERFLY = 45
MINIGAME_DAILY_CHANCE = 46
MINIGAME_PINECONE_POP = 47
MINIGAME_LIGHT_PIPE = 48
MINIGAME_GEM_JUGGLE = 49
MINIGAME_KNITTING = 50
MINIGAME_SHEARING = 51
MINIGAME_BUTTON_SEARCH = 52

# Map zone IDs to game IDs
ZONE_TO_GAME: dict[int, int] = {
    ZoneConstants.FIREFLY_LIGHT_UP_GAME: MINIGAME_FIREFLY_LIGHT_UP,
    ZoneConstants.BUBBLE_BOUNCE_GAME: MINIGAME_BUBBLE_BOUNCE,
    ZoneConstants.WATER_WEB_GAME: MINIGAME_WATER_WEB,
    ZoneConstants.HARVEST_HUSTLE_GAME: MINIGAME_HARVEST_HUSTLE,
    ZoneConstants.PETAL_PICKUP_GAME: MINIGAME_PETAL_PICKUP,
    ZoneConstants.FAIRY_FIREWORKS_GAME: MINIGAME_FAIRY_FIREWORKS,
    ZoneConstants.SNOWFLAKE_SWEEP_GAME: MINIGAME_SNOWFLAKE_SWEEP,
    ZoneConstants.TINKER_TOSS_GAME: MINIGAME_TINKER_TOSS,
    ZoneConstants.SNOWY_LULLABY_GAME: MINIGAME_LULLABY,
    ZoneConstants.SEED_SORTING_GAME: MINIGAME_SEED_SORTING,
    ZoneConstants.FIRST_FLIGHT_GAME: MINIGAME_FIRST_FLIGHT,
    ZoneConstants.BUTTERFLY_PAINTER_GAME: MINIGAME_BUTTERFLY,
    ZoneConstants.VIDIAS_DAILY_SPIN: MINIGAME_DAILY_CHANCE,
    ZoneConstants.PINECONE_POP_GAME: MINIGAME_PINECONE_POP,
    ZoneConstants.LIGHT_PIPE_GAME: MINIGAME_LIGHT_PIPE,
    ZoneConstants.GEM_JUGGLE_GAME: MINIGAME_GEM_JUGGLE
}

def getGameIdForZone(zoneId: int) -> int | None:
    """Get the game ID for a given zone, if it's a game zone"""
    return ZONE_TO_GAME.get(zoneId)
