# Minigame IDs (from constants)
MINIGAME_FIREFLY_LIGHT_UP = 1
MINIGAME_BUBBLE_BOUNCE = 2
MINIGAME_CATERPILLAR_CUTTER = 3
MINIGAME_PATTERN_PLACING = 4
MINIGAME_SPIDER_STITCHING = 5
MINIGAME_ROLLYPOLLY_DYING = 6
MINIGAME_WATER_WEB = 7
MINIGAME_HARVEST_HUSTLE = 8
MINIGAME_PETAL_PICKUP = 9
MINIGAME_FAIRY_FIREWORKS = 10
MINIGAME_SNOWFLAKE_SWEEP = 11
MINIGAME_PASS_POPCORN = 12
MINIGAME_SIMONE_SAYS = 13
MINIGAME_TINKER_TOSS = 14
MINIGAME_LULLABY = 15
MINIGAME_ROCK_PAPER_SCISSOR = 16
MINIGAME_POURING = 38
MINIGAME_BAKING = 39
MINIGAME_MIXING = 40
MINIGAME_TINKERING = 41
MINIGAME_SORTING_SUPPLIES_TUTORIAL = 42
MINIGAME_SEED_SORTING = 43
MINIGAME_FIRST_FLIGHT = 44
MINIGAME_BUTTERFLY = 45
MINIGAME_DAILY_CHANCE = 46
MINIGAME_PINECONE_POP = 47
MINIGAME_LIGHT_PIPE = 48
MINIGAME_GEM_JUGGLE = 49
MINIGAME_KNITTING = 50
MINIGAME_SHEARING = 51
MINIGAME_BUTTON_SEARCH = 52

# Map zone IDs to game IDs (you'll need to fill this in)
ZONE_TO_GAME = {
    50001: MINIGAME_FIREFLY_LIGHT_UP,
    50002: MINIGAME_BUBBLE_BOUNCE,
    50007: MINIGAME_WATER_WEB,
    50008: MINIGAME_HARVEST_HUSTLE,
    50009: MINIGAME_PETAL_PICKUP,
    50010: MINIGAME_FAIRY_FIREWORKS,
    50011: MINIGAME_SNOWFLAKE_SWEEP,
    50014: MINIGAME_TINKER_TOSS,
    50015: MINIGAME_LULLABY,
    50043: MINIGAME_SEED_SORTING,
    50044: MINIGAME_FIRST_FLIGHT,
    50045: MINIGAME_BUTTERFLY,
    50046: MINIGAME_DAILY_CHANCE,
    50047: MINIGAME_PINECONE_POP,
    50048: MINIGAME_LIGHT_PIPE,
    50049: MINIGAME_GEM_JUGGLE

    # Add more as you discover them
}

def getGameIdForZone(zoneId):
    """Get the game ID for a given zone, if it's a game zone"""
    return ZONE_TO_GAME.get(zoneId)
